apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piston-packages-pvc
  namespace: piston
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 100Gi
